# Generated by Django 5.1 on 2024-11-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fill_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('sent_tracking_number', models.CharField(max_length=50)),
                ('return_tracking_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
