# Generated by Django 5.1 on 2024-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
