# Generated by Django 5.1 on 2024-11-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='sent_tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
