# Generated by Django 5.1 on 2024-11-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='操作描述'),
        ),
    ]
