# Generated by Django 5.1 on 2024-11-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_useractionlog_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
