# Generated by Django 5.1 on 2024-11-12 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_userquerycount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquerycount',
            name='query_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquerycount',
            name='query_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='userquerycount',
            unique_together={('user', 'query_date')},
        ),
    ]
