# Generated by Django 5.1 on 2024-11-12 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_delete_userquerycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQueryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField(default=django.utils.timezone.now)),
                ('query_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
