# Generated by Django 5.1 on 2024-11-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_actionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
