# Generated by Django 5.1 on 2024-11-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_actionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
