# Generated by Django 5.1 on 2024-11-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_actionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
